### ISSUE TITLE
Support "-v" shorthand for version 

### ISSUE THREAD

**Issue by sarkiroka** [shiwaforce/poco#46]
poco - -version works well but the short is industry standard, please support it, for check the actual version of poco.

**Comment by csabalep** [comment]
poco -v is the short version of --verbose and that is an industry standard too.

**Comment by sarkiroka** [comment]
You right, sometimes some app use "-v" for verbose. Aren't you going to do a shorthand for version check?
I know, this is a little feature, but I many times tries "poco -v" (in a last few months) because my routine is the most of application use "-v" to prints its version. And I always failed. That is why I made this ticket.

**Comment by sarkiroka** [comment]
And what if when I used only the "-v" without any parameters, poco writes the version string, and when I use any parameter, the "-v" behaves like "--verbose"
So
`poco -v` -> prints the version string
`poco -v parameter` -> turn on the verbose mode

**Comment by antonkovach** [comment]
-V verbose, -v version?
