### ISSUE TITLE
[FEATURE REQUEST] Run Init containers before a plan

### ISSUE THREAD

**Issue by petercseh-sf** [shiwaforce/poco#63]
Hi!

Please consider developing a feature for kubernetes like init containers. See:
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

So I can avoid using docker compose's horrid wait-for-it.sh scripts when I want to wait for a container to start properly before my. 
https://docs.docker.com/compose/startup-order/

**Comment by gaborkolarovics** [comment]
0.98.0 release
