### ISSUE TITLE
[FEATURE REQUEST] before_script logging 

### ISSUE THREAD

**Issue by petercseh** [shiwaforce/poco#66]
I would find it very helpful if I could read any form of logging of my commands declared in poco.yml before_script part.

Right now I have no idea if they were executed or not at all. 
Did all of them complete correctly? 

I wish to see the declared command logged on my terminal for clarity.

**Comment by sarkiroka** [comment]
when you start your script with "set -x", the shell can prints the commands. https://stackoverflow.com/questions/36273665/what-does-set-x-do
@petercseh  can you use it?

**Comment by petercseh** [comment]
Not really. 

If my before_script is inline, for example:
` - mkdir -p /my/test/folder`
then I'd like to see the exact command logged on my screen. 

> Executing before_script: "mkdir -p /my/test/folder"

If my before_script contains calls for external my-script.sh files, then I want to see which files were called.

> Executing before_script: my-script.sh

Or something similar.
