### ISSUE TITLE
echo after plan started

### ISSUE THREAD

**Issue by sarkiroka** [shiwaforce/poco#67]
when start a complex plan which usage is complex good idea print some instruction into the console. now before_script able to this, but it plan independent and always runs. the other problem with the before_script is the position: it can echos before all of output. i think good flow when started a plan, and developers needs another instrucions it can echos after "docker ps" table.
what do you think about this idea? is it possible?

**Comment by gaborkolarovics** [comment]
use after_script.

Example:
- create a TEST.md file in your project root
- put after_script in your plan:

```
    after_script:
      - command: [ 'TEST.md' ]
        image: gaborkolarovics/mdcat:latest
```
